/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_compiler = 1,
  anon_sym_LPAREN = 2,
  anon_sym_VERSION = 3,
  anon_sym_RPAREN = 4,
  anon_sym_project = 5,
  anon_sym_require = 6,
  anon_sym_EXE = 7,
  anon_sym_LIB = 8,
  anon_sym_find = 9,
  anon_sym_ifdef = 10,
  anon_sym_endif = 11,
  anon_sym_option = 12,
  anon_sym_task = 13,
  anon_sym_endtask = 14,
  anon_sym_cmd = 15,
  anon_sym_program = 16,
  anon_sym_LINK = 17,
  anon_sym_create = 18,
  anon_sym_DIR = 19,
  anon_sym_FILE = 20,
  anon_sym_copy = 21,
  anon_sym_print = 22,
  anon_sym_remove = 23,
  anon_sym_add = 24,
  anon_sym_MIN = 25,
  anon_sym_MAX = 26,
  sym_VERSION_NUMBER = 27,
  anon_sym_DQUOTE = 28,
  sym_STRING_CONTENT = 29,
  sym_ESCAPE_SEQUENCE = 30,
  sym_IDENT = 31,
  sym_COMMENT = 32,
  sym_source_file = 33,
  sym_statement = 34,
  sym_compiler = 35,
  sym_project = 36,
  sym_require = 37,
  sym_find = 38,
  sym_ifdef = 39,
  sym_option = 40,
  sym_task = 41,
  sym_cmd = 42,
  sym_program = 43,
  sym_create = 44,
  sym_copy = 45,
  sym_print = 46,
  sym_remove = 47,
  sym_add = 48,
  sym__version_spec = 49,
  sym_exact_version = 50,
  sym_min_version = 51,
  sym_max_version = 52,
  sym_version_range = 53,
  sym_STRING = 54,
  aux_sym_source_file_repeat1 = 55,
  aux_sym_program_repeat1 = 56,
  aux_sym_add_repeat1 = 57,
  aux_sym_STRING_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_compiler] = "compiler",
  [anon_sym_LPAREN] = "(",
  [anon_sym_VERSION] = "VERSION",
  [anon_sym_RPAREN] = ")",
  [anon_sym_project] = "project",
  [anon_sym_require] = "require",
  [anon_sym_EXE] = "EXE",
  [anon_sym_LIB] = "LIB",
  [anon_sym_find] = "find",
  [anon_sym_ifdef] = "ifdef",
  [anon_sym_endif] = "endif",
  [anon_sym_option] = "option",
  [anon_sym_task] = "task",
  [anon_sym_endtask] = "endtask",
  [anon_sym_cmd] = "cmd",
  [anon_sym_program] = "program",
  [anon_sym_LINK] = "LINK",
  [anon_sym_create] = "create",
  [anon_sym_DIR] = "DIR",
  [anon_sym_FILE] = "FILE",
  [anon_sym_copy] = "copy",
  [anon_sym_print] = "print",
  [anon_sym_remove] = "remove",
  [anon_sym_add] = "add",
  [anon_sym_MIN] = "MIN",
  [anon_sym_MAX] = "MAX",
  [sym_VERSION_NUMBER] = "VERSION_NUMBER",
  [anon_sym_DQUOTE] = "\"",
  [sym_STRING_CONTENT] = "STRING_CONTENT",
  [sym_ESCAPE_SEQUENCE] = "ESCAPE_SEQUENCE",
  [sym_IDENT] = "IDENT",
  [sym_COMMENT] = "COMMENT",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_compiler] = "compiler",
  [sym_project] = "project",
  [sym_require] = "require",
  [sym_find] = "find",
  [sym_ifdef] = "ifdef",
  [sym_option] = "option",
  [sym_task] = "task",
  [sym_cmd] = "cmd",
  [sym_program] = "program",
  [sym_create] = "create",
  [sym_copy] = "copy",
  [sym_print] = "print",
  [sym_remove] = "remove",
  [sym_add] = "add",
  [sym__version_spec] = "_version_spec",
  [sym_exact_version] = "exact_version",
  [sym_min_version] = "min_version",
  [sym_max_version] = "max_version",
  [sym_version_range] = "version_range",
  [sym_STRING] = "STRING",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_add_repeat1] = "add_repeat1",
  [aux_sym_STRING_repeat1] = "STRING_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_compiler] = anon_sym_compiler,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_VERSION] = anon_sym_VERSION,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_project] = anon_sym_project,
  [anon_sym_require] = anon_sym_require,
  [anon_sym_EXE] = anon_sym_EXE,
  [anon_sym_LIB] = anon_sym_LIB,
  [anon_sym_find] = anon_sym_find,
  [anon_sym_ifdef] = anon_sym_ifdef,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_task] = anon_sym_task,
  [anon_sym_endtask] = anon_sym_endtask,
  [anon_sym_cmd] = anon_sym_cmd,
  [anon_sym_program] = anon_sym_program,
  [anon_sym_LINK] = anon_sym_LINK,
  [anon_sym_create] = anon_sym_create,
  [anon_sym_DIR] = anon_sym_DIR,
  [anon_sym_FILE] = anon_sym_FILE,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_remove] = anon_sym_remove,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_MIN] = anon_sym_MIN,
  [anon_sym_MAX] = anon_sym_MAX,
  [sym_VERSION_NUMBER] = sym_VERSION_NUMBER,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_STRING_CONTENT] = sym_STRING_CONTENT,
  [sym_ESCAPE_SEQUENCE] = sym_ESCAPE_SEQUENCE,
  [sym_IDENT] = sym_IDENT,
  [sym_COMMENT] = sym_COMMENT,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_compiler] = sym_compiler,
  [sym_project] = sym_project,
  [sym_require] = sym_require,
  [sym_find] = sym_find,
  [sym_ifdef] = sym_ifdef,
  [sym_option] = sym_option,
  [sym_task] = sym_task,
  [sym_cmd] = sym_cmd,
  [sym_program] = sym_program,
  [sym_create] = sym_create,
  [sym_copy] = sym_copy,
  [sym_print] = sym_print,
  [sym_remove] = sym_remove,
  [sym_add] = sym_add,
  [sym__version_spec] = sym__version_spec,
  [sym_exact_version] = sym_exact_version,
  [sym_min_version] = sym_min_version,
  [sym_max_version] = sym_max_version,
  [sym_version_range] = sym_version_range,
  [sym_STRING] = sym_STRING,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_add_repeat1] = aux_sym_add_repeat1,
  [aux_sym_STRING_repeat1] = aux_sym_STRING_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_compiler] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VERSION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_project] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_require] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EXE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LIB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_find] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ifdef] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endtask] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_program] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LINK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_create] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DIR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FILE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_remove] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MIN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MAX] = {
    .visible = true,
    .named = false,
  },
  [sym_VERSION_NUMBER] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_STRING_CONTENT] = {
    .visible = true,
    .named = true,
  },
  [sym_ESCAPE_SEQUENCE] = {
    .visible = true,
    .named = true,
  },
  [sym_IDENT] = {
    .visible = true,
    .named = true,
  },
  [sym_COMMENT] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_compiler] = {
    .visible = true,
    .named = true,
  },
  [sym_project] = {
    .visible = true,
    .named = true,
  },
  [sym_require] = {
    .visible = true,
    .named = true,
  },
  [sym_find] = {
    .visible = true,
    .named = true,
  },
  [sym_ifdef] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_create] = {
    .visible = true,
    .named = true,
  },
  [sym_copy] = {
    .visible = true,
    .named = true,
  },
  [sym_print] = {
    .visible = true,
    .named = true,
  },
  [sym_remove] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym__version_spec] = {
    .visible = false,
    .named = true,
  },
  [sym_exact_version] = {
    .visible = true,
    .named = true,
  },
  [sym_min_version] = {
    .visible = true,
    .named = true,
  },
  [sym_max_version] = {
    .visible = true,
    .named = true,
  },
  [sym_version_range] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_add_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_STRING_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(85);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(113);
      if (lookahead == '(') ADVANCE(87);
      if (lookahead == ')') ADVANCE(89);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == 'D') ADVANCE(11);
      if (lookahead == 'E') ADVANCE(24);
      if (lookahead == 'F') ADVANCE(12);
      if (lookahead == 'L') ADVANCE(13);
      if (lookahead == 'M') ADVANCE(6);
      if (lookahead == 'V') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead == 'c') ADVANCE(60);
      if (lookahead == 'e') ADVANCE(63);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(67);
      if (lookahead == 'p') ADVANCE(69);
      if (lookahead == 'r') ADVANCE(36);
      if (lookahead == 't') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(114);
      if (lookahead == '"') ADVANCE(113);
      if (lookahead == '\\') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    case 2:
      if (lookahead == '\r') SKIP(2);
      if (lookahead == ')') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(118);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(23);
      if (lookahead == 'I') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'B') ADVANCE(93);
      if (lookahead == 'N') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(92);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(105);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'I') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'I') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'I') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'I') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'K') ADVANCE(102);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'N') ADVANCE(110);
      END_STATE();
    case 18:
      if (lookahead == 'N') ADVANCE(88);
      END_STATE();
    case 19:
      if (lookahead == 'O') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'R') ADVANCE(104);
      END_STATE();
    case 21:
      if (lookahead == 'R') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'S') ADVANCE(14);
      END_STATE();
    case 23:
      if (lookahead == 'X') ADVANCE(111);
      END_STATE();
    case 24:
      if (lookahead == 'X') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(76);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(109);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(100);
      END_STATE();
    case 32:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(94);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(96);
      END_STATE();
    case 45:
      if (lookahead == 'f') ADVANCE(95);
      END_STATE();
    case 46:
      if (lookahead == 'f') ADVANCE(35);
      END_STATE();
    case 47:
      if (lookahead == 'g') ADVANCE(71);
      if (lookahead == 'j') ADVANCE(37);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(62);
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(66);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'k') ADVANCE(98);
      END_STATE();
    case 55:
      if (lookahead == 'k') ADVANCE(99);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 57:
      if (lookahead == 'm') ADVANCE(65);
      if (lookahead == 'q') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'm') ADVANCE(101);
      END_STATE();
    case 59:
      if (lookahead == 'm') ADVANCE(68);
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'm') ADVANCE(31);
      if (lookahead == 'o') ADVANCE(59);
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(80);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 67:
      if (lookahead == 'p') ADVANCE(77);
      END_STATE();
    case 68:
      if (lookahead == 'p') ADVANCE(48);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 80:
      if (lookahead == 'v') ADVANCE(39);
      END_STATE();
    case 81:
      if (lookahead == 'y') ADVANCE(106);
      END_STATE();
    case 82:
      ADVANCE_MAP(
        '"', 116,
        '\'', 116,
        '\\', 116,
        'b', 116,
        'f', 116,
        'n', 116,
        'r', 116,
        't', 116,
        'v', 116,
      );
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 84:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_compiler);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_VERSION);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_project);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_require);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_EXE);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LIB);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_find);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_ifdef);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_task);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_endtask);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_cmd);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_program);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LINK);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_create);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_DIR);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_FILE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_remove);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_MIN);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_MAX);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_VERSION_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_STRING_CONTENT);
      if (lookahead == '\r') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_STRING_CONTENT);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_ESCAPE_SEQUENCE);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_IDENT);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_COMMENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(118);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_compiler] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_VERSION] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_project] = ACTIONS(1),
    [anon_sym_require] = ACTIONS(1),
    [anon_sym_EXE] = ACTIONS(1),
    [anon_sym_LIB] = ACTIONS(1),
    [anon_sym_find] = ACTIONS(1),
    [anon_sym_ifdef] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_task] = ACTIONS(1),
    [anon_sym_endtask] = ACTIONS(1),
    [anon_sym_cmd] = ACTIONS(1),
    [anon_sym_program] = ACTIONS(1),
    [anon_sym_LINK] = ACTIONS(1),
    [anon_sym_create] = ACTIONS(1),
    [anon_sym_DIR] = ACTIONS(1),
    [anon_sym_FILE] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_remove] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_MIN] = ACTIONS(1),
    [anon_sym_MAX] = ACTIONS(1),
    [sym_VERSION_NUMBER] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_ESCAPE_SEQUENCE] = ACTIONS(1),
    [sym_COMMENT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(65),
    [sym_statement] = STATE(3),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(2),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_compiler] = ACTIONS(37),
    [anon_sym_project] = ACTIONS(40),
    [anon_sym_require] = ACTIONS(43),
    [anon_sym_find] = ACTIONS(46),
    [anon_sym_ifdef] = ACTIONS(49),
    [anon_sym_endif] = ACTIONS(35),
    [anon_sym_option] = ACTIONS(52),
    [anon_sym_task] = ACTIONS(55),
    [anon_sym_endtask] = ACTIONS(35),
    [anon_sym_cmd] = ACTIONS(58),
    [anon_sym_program] = ACTIONS(61),
    [anon_sym_create] = ACTIONS(64),
    [anon_sym_copy] = ACTIONS(67),
    [anon_sym_print] = ACTIONS(70),
    [anon_sym_remove] = ACTIONS(73),
    [anon_sym_add] = ACTIONS(76),
    [sym_COMMENT] = ACTIONS(79),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(2),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym_statement] = STATE(6),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_endif] = ACTIONS(84),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
  [STATE(5)] = {
    [sym_statement] = STATE(7),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_endtask] = ACTIONS(86),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
  [STATE(6)] = {
    [sym_statement] = STATE(2),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_endif] = ACTIONS(88),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
  [STATE(7)] = {
    [sym_statement] = STATE(2),
    [sym_compiler] = STATE(13),
    [sym_project] = STATE(13),
    [sym_require] = STATE(13),
    [sym_find] = STATE(13),
    [sym_ifdef] = STATE(13),
    [sym_option] = STATE(13),
    [sym_task] = STATE(13),
    [sym_cmd] = STATE(13),
    [sym_program] = STATE(13),
    [sym_create] = STATE(13),
    [sym_copy] = STATE(13),
    [sym_print] = STATE(13),
    [sym_remove] = STATE(13),
    [sym_add] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_compiler] = ACTIONS(5),
    [anon_sym_project] = ACTIONS(7),
    [anon_sym_require] = ACTIONS(9),
    [anon_sym_find] = ACTIONS(11),
    [anon_sym_ifdef] = ACTIONS(13),
    [anon_sym_option] = ACTIONS(15),
    [anon_sym_task] = ACTIONS(17),
    [anon_sym_endtask] = ACTIONS(90),
    [anon_sym_cmd] = ACTIONS(19),
    [anon_sym_program] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(23),
    [anon_sym_copy] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [anon_sym_remove] = ACTIONS(29),
    [anon_sym_add] = ACTIONS(31),
    [sym_COMMENT] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(92), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [21] = 1,
    ACTIONS(94), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [42] = 1,
    ACTIONS(96), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [63] = 1,
    ACTIONS(98), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [84] = 1,
    ACTIONS(100), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [105] = 1,
    ACTIONS(102), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [126] = 1,
    ACTIONS(104), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [147] = 1,
    ACTIONS(106), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [168] = 1,
    ACTIONS(108), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [189] = 1,
    ACTIONS(110), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [210] = 1,
    ACTIONS(112), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [231] = 1,
    ACTIONS(114), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [252] = 1,
    ACTIONS(116), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [273] = 1,
    ACTIONS(118), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [294] = 1,
    ACTIONS(120), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [315] = 1,
    ACTIONS(122), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [336] = 1,
    ACTIONS(124), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [357] = 1,
    ACTIONS(126), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [378] = 1,
    ACTIONS(128), 18,
      ts_builtin_sym_end,
      anon_sym_compiler,
      anon_sym_project,
      anon_sym_require,
      anon_sym_find,
      anon_sym_ifdef,
      anon_sym_endif,
      anon_sym_option,
      anon_sym_task,
      anon_sym_endtask,
      anon_sym_cmd,
      anon_sym_program,
      anon_sym_create,
      anon_sym_copy,
      anon_sym_print,
      anon_sym_remove,
      anon_sym_add,
      sym_COMMENT,
  [399] = 4,
    ACTIONS(130), 1,
      anon_sym_MIN,
    ACTIONS(132), 1,
      anon_sym_MAX,
    ACTIONS(134), 1,
      sym_VERSION_NUMBER,
    STATE(92), 5,
      sym__version_spec,
      sym_exact_version,
      sym_min_version,
      sym_max_version,
      sym_version_range,
  [416] = 3,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    STATE(28), 2,
      sym_STRING,
      aux_sym_add_repeat1,
  [427] = 4,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      sym_STRING_CONTENT,
    ACTIONS(145), 1,
      sym_ESCAPE_SEQUENCE,
    STATE(32), 1,
      aux_sym_STRING_repeat1,
  [440] = 4,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    ACTIONS(149), 1,
      sym_STRING_CONTENT,
    ACTIONS(151), 1,
      sym_ESCAPE_SEQUENCE,
    STATE(29), 1,
      aux_sym_STRING_repeat1,
  [453] = 3,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(28), 2,
      sym_STRING,
      aux_sym_add_repeat1,
  [464] = 4,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_STRING_CONTENT,
    ACTIONS(162), 1,
      sym_ESCAPE_SEQUENCE,
    STATE(32), 1,
      aux_sym_STRING_repeat1,
  [477] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(31), 2,
      sym_STRING,
      aux_sym_add_repeat1,
  [485] = 3,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 1,
      sym_IDENT,
    STATE(34), 1,
      aux_sym_program_repeat1,
  [495] = 3,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 1,
      sym_IDENT,
    STATE(34), 1,
      aux_sym_program_repeat1,
  [505] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(72), 1,
      sym_STRING,
  [512] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      sym_STRING,
  [519] = 1,
    ACTIONS(174), 2,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
  [524] = 2,
    ACTIONS(176), 1,
      sym_IDENT,
    STATE(35), 1,
      aux_sym_program_repeat1,
  [531] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_STRING,
  [538] = 2,
    ACTIONS(178), 1,
      anon_sym_VERSION,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
  [545] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_STRING,
  [552] = 1,
    ACTIONS(182), 2,
      anon_sym_EXE,
      anon_sym_LIB,
  [557] = 2,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      anon_sym_MAX,
  [564] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(98), 1,
      sym_STRING,
  [571] = 1,
    ACTIONS(188), 2,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
  [576] = 2,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    ACTIONS(192), 1,
      anon_sym_LINK,
  [583] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_STRING,
  [590] = 1,
    ACTIONS(194), 2,
      anon_sym_DIR,
      anon_sym_FILE,
  [595] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_STRING,
  [602] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_STRING,
  [609] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      sym_STRING,
  [616] = 1,
    ACTIONS(196), 2,
      anon_sym_DIR,
      anon_sym_FILE,
  [621] = 2,
    ACTIONS(134), 1,
      sym_VERSION_NUMBER,
    STATE(73), 1,
      sym_exact_version,
  [628] = 1,
    ACTIONS(198), 2,
      anon_sym_DIR,
      anon_sym_FILE,
  [633] = 1,
    ACTIONS(200), 2,
      anon_sym_EXE,
      anon_sym_LIB,
  [638] = 2,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(70), 1,
      sym_STRING,
  [645] = 1,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
  [649] = 1,
    ACTIONS(204), 1,
      anon_sym_LPAREN,
  [653] = 1,
    ACTIONS(206), 1,
      anon_sym_LPAREN,
  [657] = 1,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
  [661] = 1,
    ACTIONS(210), 1,
      anon_sym_LPAREN,
  [665] = 1,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
  [669] = 1,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
  [673] = 1,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
  [677] = 1,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
  [681] = 1,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
  [685] = 1,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
  [689] = 1,
    ACTIONS(224), 1,
      anon_sym_VERSION,
  [693] = 1,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
  [697] = 1,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
  [701] = 1,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
  [705] = 1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [709] = 1,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
  [713] = 1,
    ACTIONS(236), 1,
      sym_IDENT,
  [717] = 1,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
  [721] = 1,
    ACTIONS(240), 1,
      anon_sym_LPAREN,
  [725] = 1,
    ACTIONS(242), 1,
      anon_sym_LPAREN,
  [729] = 1,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
  [733] = 1,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
  [737] = 1,
    ACTIONS(248), 1,
      sym_IDENT,
  [741] = 1,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
  [745] = 1,
    ACTIONS(252), 1,
      sym_VERSION_NUMBER,
  [749] = 1,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [753] = 1,
    ACTIONS(256), 1,
      sym_VERSION_NUMBER,
  [757] = 1,
    ACTIONS(258), 1,
      sym_VERSION_NUMBER,
  [761] = 1,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
  [765] = 1,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [769] = 1,
    ACTIONS(264), 1,
      anon_sym_LPAREN,
  [773] = 1,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [777] = 1,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
  [781] = 1,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [785] = 1,
    ACTIONS(272), 1,
      anon_sym_LPAREN,
  [789] = 1,
    ACTIONS(274), 1,
      anon_sym_LPAREN,
  [793] = 1,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
  [797] = 1,
    ACTIONS(278), 1,
      sym_IDENT,
  [801] = 1,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
  [805] = 1,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [809] = 1,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [813] = 1,
    ACTIONS(286), 1,
      anon_sym_LPAREN,
  [817] = 1,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
  [821] = 1,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 21,
  [SMALL_STATE(10)] = 42,
  [SMALL_STATE(11)] = 63,
  [SMALL_STATE(12)] = 84,
  [SMALL_STATE(13)] = 105,
  [SMALL_STATE(14)] = 126,
  [SMALL_STATE(15)] = 147,
  [SMALL_STATE(16)] = 168,
  [SMALL_STATE(17)] = 189,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 231,
  [SMALL_STATE(20)] = 252,
  [SMALL_STATE(21)] = 273,
  [SMALL_STATE(22)] = 294,
  [SMALL_STATE(23)] = 315,
  [SMALL_STATE(24)] = 336,
  [SMALL_STATE(25)] = 357,
  [SMALL_STATE(26)] = 378,
  [SMALL_STATE(27)] = 399,
  [SMALL_STATE(28)] = 416,
  [SMALL_STATE(29)] = 427,
  [SMALL_STATE(30)] = 440,
  [SMALL_STATE(31)] = 453,
  [SMALL_STATE(32)] = 464,
  [SMALL_STATE(33)] = 477,
  [SMALL_STATE(34)] = 485,
  [SMALL_STATE(35)] = 495,
  [SMALL_STATE(36)] = 505,
  [SMALL_STATE(37)] = 512,
  [SMALL_STATE(38)] = 519,
  [SMALL_STATE(39)] = 524,
  [SMALL_STATE(40)] = 531,
  [SMALL_STATE(41)] = 538,
  [SMALL_STATE(42)] = 545,
  [SMALL_STATE(43)] = 552,
  [SMALL_STATE(44)] = 557,
  [SMALL_STATE(45)] = 564,
  [SMALL_STATE(46)] = 571,
  [SMALL_STATE(47)] = 576,
  [SMALL_STATE(48)] = 583,
  [SMALL_STATE(49)] = 590,
  [SMALL_STATE(50)] = 595,
  [SMALL_STATE(51)] = 602,
  [SMALL_STATE(52)] = 609,
  [SMALL_STATE(53)] = 616,
  [SMALL_STATE(54)] = 621,
  [SMALL_STATE(55)] = 628,
  [SMALL_STATE(56)] = 633,
  [SMALL_STATE(57)] = 638,
  [SMALL_STATE(58)] = 645,
  [SMALL_STATE(59)] = 649,
  [SMALL_STATE(60)] = 653,
  [SMALL_STATE(61)] = 657,
  [SMALL_STATE(62)] = 661,
  [SMALL_STATE(63)] = 665,
  [SMALL_STATE(64)] = 669,
  [SMALL_STATE(65)] = 673,
  [SMALL_STATE(66)] = 677,
  [SMALL_STATE(67)] = 681,
  [SMALL_STATE(68)] = 685,
  [SMALL_STATE(69)] = 689,
  [SMALL_STATE(70)] = 693,
  [SMALL_STATE(71)] = 697,
  [SMALL_STATE(72)] = 701,
  [SMALL_STATE(73)] = 705,
  [SMALL_STATE(74)] = 709,
  [SMALL_STATE(75)] = 713,
  [SMALL_STATE(76)] = 717,
  [SMALL_STATE(77)] = 721,
  [SMALL_STATE(78)] = 725,
  [SMALL_STATE(79)] = 729,
  [SMALL_STATE(80)] = 733,
  [SMALL_STATE(81)] = 737,
  [SMALL_STATE(82)] = 741,
  [SMALL_STATE(83)] = 745,
  [SMALL_STATE(84)] = 749,
  [SMALL_STATE(85)] = 753,
  [SMALL_STATE(86)] = 757,
  [SMALL_STATE(87)] = 761,
  [SMALL_STATE(88)] = 765,
  [SMALL_STATE(89)] = 769,
  [SMALL_STATE(90)] = 773,
  [SMALL_STATE(91)] = 777,
  [SMALL_STATE(92)] = 781,
  [SMALL_STATE(93)] = 785,
  [SMALL_STATE(94)] = 789,
  [SMALL_STATE(95)] = 793,
  [SMALL_STATE(96)] = 797,
  [SMALL_STATE(97)] = 801,
  [SMALL_STATE(98)] = 805,
  [SMALL_STATE(99)] = 809,
  [SMALL_STATE(100)] = 813,
  [SMALL_STATE(101)] = 817,
  [SMALL_STATE(102)] = 821,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remove, 5, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 8, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compiler, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 6, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy, 6, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifdef, 7, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 7, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifdef, 8, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_add_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_STRING_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_STRING_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_STRING_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_STRING, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min_version, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_STRING, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [216] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max_version, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exact_version, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_range, 4, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_c3_build_file(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "c3_build_file",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
